### PR TITLE
91 update actions to include new services config

### LINKED ISSUE #91: Update Actions to include new services config
New REST client stuff requires local folder and config file otherwise startup fails.
Next release will provide code fix to be resilient to crash, but this issue is to add non code content to actions to ensure current release succeeds.

Desired location in final packaging:

Image

What's in side that services folder:
 
Image

Attached are the files I used for Alpha testing. I realize now why I did not add the defaultRestAccessLayer.json file to the github repo... it had org specific URL in it. The attached is a clean file (removed references).

[captionPrompt.txt](https://github.com/user-attachments/files/19647773/captionPrompt.txt)
[readme.md](https://github.com/user-attachments/files/19647775/readme.md)
[autochooseCaptionPrompt.txt](https://github.com/user-attachments/files/19647776/autochooseCaptionPrompt.txt)

[defaultRestAccessLayer.json](https://github.com/user-attachments/files/19647800/defaultRestAccessLayer.json)

### PR DESCRIPTION
**Pull request by samypr100**
Closes #91

### CODE REVIEW

File: src/main/java/edu/jhuapl/trinity/data/messages/llm/Prompts.java [hunk 1]
```diff
@@ -16,24 +10,41 @@
  */
 public enum Prompts {
     INSTANCE;
-    public static final String PROMPTS_DEFAULT_PATH = "services/"; //default to local relative path
-    public static final String DEFAULT_CAPTION_PROMPT = "captionPrompt.txt";
-    public static final String AUTOCHOOSE_CAPTION_PROMPT = "autochooseCaptionPrompt.txt";
+    public static String PROMPTS_DEFAULT_PATH = "services/"; //default to local relative path
```
Comment (samypr100) [inline src/main/java/edu/jhuapl/trinity/data/messages/llm/Prompts.java:13]: Note, local relative path will likely not work with jpackage in other platforms

File: src/main/java/edu/jhuapl/trinity/messages/RestAccessLayer.java [hunk 2]
```diff
@@ -38,11 +38,13 @@ public enum RestAccessLayer {
     private static final Logger LOG = LoggerFactory.getLogger(RestAccessLayer.class);
     private static HttpClient httpClient;
     private static ObjectMapper objectMapper;
-    public static final String SERVICES_DEFAULT_PATH = "services/"; //default to local relative path
-    public static final String SERVICES_DEFAULT_CONFIG = "defaultRestAccessLayer.json";
+    public static String SERVICES_DEFAULT_PATH = "services/"; //default to local relative path
```
Comment (samypr100) [inline src/main/java/edu/jhuapl/trinity/messages/RestAccessLayer.java:41]: Note, local relative path is generally not compatible with jpackage

**Review by Birdasaur — DISMISSED** [review]

File: src/main/java/edu/jhuapl/trinity/data/messages/llm/Prompts.java (hunk 1 above)
Comment (samypr100) [reply src/main/java/edu/jhuapl/trinity/data/messages/llm/Prompts.java:13]: Lets use System.getProperty("trinity.app.dir") with fallback to relative directory for jar scenarios

File: src/main/java/edu/jhuapl/trinity/messages/RestAccessLayer.java (hunk 2 above)
Comment (samypr100) [reply src/main/java/edu/jhuapl/trinity/messages/RestAccessLayer.java:41]: Lets use System.getProperty("trinity.app.dir") with fallback to relative directory for jar scenarios

**Comment by Birdasaur** [comment]
Verified new updates work successfully on Windows for both Jar and JPackage logical pathways.
